#:schema node_modules/wrangler/config-schema.json
name = "bdc-backend"
main = "src/index.tsx"
compatibility_date = "2024-08-03"

# Development environment (default)
[vars]
ENVIRONMENT = "development"

# Staging environment
[env.staging]
[env.staging.vars]
ENVIRONMENT = "staging"

# Production environment  
[env.production]
[env.production.vars]
ENVIRONMENT = "production"